apiVersion: v1
appVersion: 0.3.6
description: Metrics Server is a cluster-wide aggregator of resource usage data.
name: metrics-server-helm
version: 0.0.1
keywords:
- metrics-server
home: https://github.com/sullivtr/metrics-server-helm
sources:
- https://github.com/sullivtr/metrics-server-helm
deprecated: false
